import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NavbarComponent from "@/components/ui/navbar.component";
import {PropsWithChildren} from "react";
import {DarkModeProvider} from "@/components/ui/dark-mode/dark-mode-provider.component";
import {LanguagesProvider} from "@/components/ui/languages/languages-provider.component";
import PageComponent from "@/components/features/page.component";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased size-full`}>
            <DarkModeProvider>
                <LanguagesProvider>
                    <NavbarComponent/>
                    <div className="grid grid-rows-[20px_1fr_20px] dark:bg-neutral-800 items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]">
                        <main className="size-full flex flex-col gap-8 row-start-2 items-center sm:items-start">
                            {children}
                        </main>
                    </div>
                </LanguagesProvider>
            </DarkModeProvider>
        </body>
    </html>
  );
}
