import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "../globals.css";
import NavbarComponent from "@/components/ui/navbar.component";
import {PropsWithChildren} from "react";
import {DarkModeProvider} from "@/components/ui/dark-mode/dark-mode-provider.component";
import {LanguagesProvider} from "@/components/ui/languages/languages-provider.component";
import {twMerge} from "tailwind-merge";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<PropsWithChildren>) {
    return (
        <html lang="en">
            <body className={twMerge("flex flex-col max-sm:min-h-screen antialiased sm:w-screen sm:h-screen", geistSans.className, geistSans.variable, geistMono.variable)}>
                <DarkModeProvider>
                    <LanguagesProvider>
                        <NavbarComponent/>
                        <div className="h-12"/>
                        <main className="w-full h-10 grow overflow-hidden bg-white text-gray-900 dark:bg-neutral-900 dark:text-gray-50">
                            {children}
                        </main>
                    </LanguagesProvider>
                </DarkModeProvider>
            </body>
        </html>
    );
}
